name: meshchile-bot

services:
  meshchile-bot:
    image: ghcr.io/mesh-chile/meshchile-github-invite-bot:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env
    restart: unless-stopped
    volumes:
      - ../logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/bot/status"]
      interval: 30s
      timeout: 10s
      retries: 3