name: meshchile-bot-dev

services:
  meshchile-bot:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ../.env
    restart: unless-stopped
    volumes:
      - ../logs:/app/logs
      - ..:/app  # Mount source code for development
      - /app/node_modules  # Exclude node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/bot/status"]
      interval: 30s
      timeout: 10s
      retries: 3
